# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PointDefine.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PointDefine.proto',
  package='',
  serialized_pb='\n\x11PointDefine.proto\"i\n\tpointlist\x12\x10\n\x08iGpsTime\x18\x01 \x03(\x05\x12\x10\n\x08iAzimuth\x18\x02 \x03(\x05\x12\x11\n\tfGpsSpeed\x18\x03 \x03(\x02\x12\x12\n\ndLongitude\x18\x04 \x03(\x01\x12\x11\n\tdLatitude\x18\x05 \x03(\x01\"\xd4\x01\n\x11trafficinfoheader\x12\x0f\n\x07iTileID\x18\x01 \x03(\x05\x12\x0f\n\x07iLinkID\x18\x02 \x03(\x05\x12\x10\n\x08iLinkDir\x18\x03 \x03(\x05\x12\x13\n\x0biLinkDegree\x18\x04 \x03(\x05\x12\r\n\x05iTime\x18\x05 \x03(\x05\x12\x13\n\x0bIsConnected\x18\x06 \x03(\x05\x12\x13\n\x0b\x66LinkLength\x18\x07 \x03(\x02\x12\x13\n\x0b\x66PathLength\x18\x08 \x03(\x02\x12\x15\n\rfAverageSpeed\x18\t \x03(\x02\x12\x11\n\tfMaxSpeed\x18\n \x03(\x02')




_POINTLIST = _descriptor.Descriptor(
  name='pointlist',
  full_name='pointlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iGpsTime', full_name='pointlist.iGpsTime', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iAzimuth', full_name='pointlist.iAzimuth', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fGpsSpeed', full_name='pointlist.fGpsSpeed', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dLongitude', full_name='pointlist.dLongitude', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dLatitude', full_name='pointlist.dLatitude', index=4,
      number=5, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=21,
  serialized_end=126,
)


_TRAFFICINFOHEADER = _descriptor.Descriptor(
  name='trafficinfoheader',
  full_name='trafficinfoheader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iTileID', full_name='trafficinfoheader.iTileID', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iLinkID', full_name='trafficinfoheader.iLinkID', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iLinkDir', full_name='trafficinfoheader.iLinkDir', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iLinkDegree', full_name='trafficinfoheader.iLinkDegree', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iTime', full_name='trafficinfoheader.iTime', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='IsConnected', full_name='trafficinfoheader.IsConnected', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fLinkLength', full_name='trafficinfoheader.fLinkLength', index=6,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fPathLength', full_name='trafficinfoheader.fPathLength', index=7,
      number=8, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fAverageSpeed', full_name='trafficinfoheader.fAverageSpeed', index=8,
      number=9, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fMaxSpeed', full_name='trafficinfoheader.fMaxSpeed', index=9,
      number=10, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=129,
  serialized_end=341,
)

DESCRIPTOR.message_types_by_name['pointlist'] = _POINTLIST
DESCRIPTOR.message_types_by_name['trafficinfoheader'] = _TRAFFICINFOHEADER

class pointlist(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _POINTLIST

  # @@protoc_insertion_point(class_scope:pointlist)

class trafficinfoheader(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TRAFFICINFOHEADER

  # @@protoc_insertion_point(class_scope:trafficinfoheader)


# @@protoc_insertion_point(module_scope)
